name: Lighthouse Audit

on:
  push:
    branches:
      - feat/lighthouse

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install
        run: |
          npm ci
      - name: Build
        run: |
          npm run build
      - name: Lighthouse CI Action
        uses: treosh/lighthouse-ci-action@v2
        with:
          # List of URL(s) to analyze
          urls: |
            https://www.strv.io
            https://www.strv.io/tools
      - name: Run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.3.x
          lhci autorun --upload.target=temporary-public-storage --collect.url=https://www.strv.io
      - name: Running Page Speed Insights
        uses: jakepartusch/psi-action@v1
        with:
          url: https://www.strv.io
