# https://github.com/marketplace/actions/lighthouse-ci-action
name: Lighthouse CI action

on:
  push:
    branches:
      - feat/lighthouse

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v3
        with:
          urls: |
            https://www.strv.io/
            https://www.strv.io/tools
          configPath: '.lighthouserc.js'
          serverBaseUrl: ${{ secrets.LHCI_SERVER_URL }}
          serverToken: ${{ secrets.LHCI_SERVER_TOKEN }}
