name: WebPageTest

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1.4.0
        with:
          working-directory: .github/actions/get-netlify-preview
      - name: Get Netlify Preview
        id: getNetlifyPreview
        uses: ./.github/actions/get-netlify-preview
        env:
          NETLIFY_API_KEY: ${{ secrets.NETLIFY_API_KEY }}
          NETLIFY_SITE_NAME: ${{ secrets.NETLIFY_SITE_NAME }}
          NETLIFY_API_ID: ${{ secrets.NETLIFY_API_ID }}
      - name: WebPageTest
        uses: JCofman/webPagetestAction@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TEST_URL: ${{ steps.getNetlifyPreview.outputs.url }}
          WEBPAGETEST_API_KEY: ${{ secrets.WEBPAGETEST_API_KEY }}
